{% set name = "dopo" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1.0') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  ignore_prefix_files: true

requirements:
  build:
    - python
    - pip
  run:
    - bw2analyzer
    - bw2calc
    - bw2data
    - dash-bootstrap-components
    - dash-daq
    - numpy
    - openpyxl
    - pandas
    - plotly
    - pytest
    - PyYAML
    - tabulate
    - scipy==1.14.1


test:
  imports:
    - dopo
  commands:
    - python -c "import dopo"

about:
  home: https://github.com/Laboratory-for-Energy-Systems-Analysis/dopo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Detecting Outliers in Premise Operations (dopo) - LCA background analysis toolkit"

extra:
  recipe-maintainers:
    - romainsacchi
