{% set name = "dopo" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.2') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  ignore_prefix_files: true
  script: bash build.sh

requirements:
  build:
    - python
    - pip
  run:
    - dash-bootstrap-components
    - dash-daq
    - numpy<2.0.0
    - openpyxl
    - pandas
    - plotly
    - pytest
    - PyYAML
    - tabulate


test:
  imports:
    - dopo
  requires:
    - bw2data
    - bw2calc
    - bw2io
    - bw2analyzer
  commands:
    - python -c "import dopo"
    - dopo-dash --help

about:
  home: https://github.com/Laboratory-for-Energy-Systems-Analysis/dopo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Detecting Outliers in Premise Operations (dopo) - LCA background analysis toolkit"

extra:
  recipe-maintainers:
    - romainsacchi
